## json mini project

In [1]:
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize

### Question 1- Find the 10 countries with the most project
1. Loaded the data set using pd.read_json
2. Viewed the data information by looking at df.head()
3. Looked at the column names
4. Looked at country names for 20
5. Created a dataframe for 10 countries with highest project count
    1. renamed the columns
    2. changed the index name
    3. Reset the index
6. Printed the results

In [33]:
#loaded the dataset using pd.read_json
df = pd.read_json('data_wrangling_json/data/world_bank_projects.json')
# View the head of df 
df.head()
#Looking at the column names
for col in df.columns: 
    print(col) 
#look at the countryname column
df.countryname.head(20)
# Use Index.value_counts() function to count the number of unique values in the given Index.
df_10 = df.countryname.value_counts().head(10)
#Creating a dataframe of the 10 countries with the highest project counts. 
country_topten = pd.DataFrame(df_10,index = None)
#index.rename(columns=) to rename the column name 
country_topten.rename(columns={'countryname':'Count'}, inplace=True)
#change the index name 
country_topten.index.name='Country Name'
#reset the index
country_topten=country_topten.reset_index()
#printing the results
print(country_topten)

_id
approvalfy
board_approval_month
boardapprovaldate
borrower
closingdate
country_namecode
countrycode
countryname
countryshortname
docty
envassesmentcategorycode
grantamt
ibrdcommamt
id
idacommamt
impagency
lendinginstr
lendinginstrtype
lendprojectcost
majorsector_percent
mjsector_namecode
mjtheme
mjtheme_namecode
mjthemecode
prodline
prodlinetext
productlinetype
project_abstract
project_name
projectdocs
projectfinancialtype
projectstatusdisplay
regionname
sector
sector1
sector2
sector3
sector4
sector_namecode
sectorcode
source
status
supplementprojectflg
theme1
theme_namecode
themecode
totalamt
totalcommamt
url
                      Country Name  Count
0            Republic of Indonesia     19
1       People's Republic of China     19
2    Socialist Republic of Vietnam     17
3                Republic of India     16
4                Republic of Yemen     13
5  People's Republic of Bangladesh     12
6                            Nepal     12
7               Kingdom of Morocco     12
8           Republic of Mozambique     11
9                           Africa     11

### Question 2-Find the top 10 major project themes (using column 'mjtheme_namecode')
1. Flattened and stored the mjtheme_namecode using json.load and normalize 
2. Explored the data using .head() and .tail()
3. Filled the Nan values with NaN.  
4. Used regular expression to look for the white spaces
    1. * | Greedily matches the expression to its left 0 or more times.
    2. ^ | Matches the expression to its right at the start of a string. It matches every such instance before each \n in the string.
    3. \s | Matches whitespace characters, which include the \t, \n, \r, and space characters.
    4. $ | Matches the expression to its left at the end of a string. It matches every such instance before each \n in the string.

5. Created a duplicate data set to look at the codes to match for the project name
    1. Sometimes csv file has null values, which are later displayed as NaN in Data Frame. Pandas dropna() method allows the user to analyze and drop Rows/Columns with Null values in different ways.
    2. Droped duplicates and sorted them
6. Turned column code to numeric using pd.to_numeric 
7. Changed project name based on code using .loc
8. Group by and sorted to see the top 10 project count

In [13]:
# Flatten and store the mjtheme_namecode column
data = json.load((open('data_wrangling_json/data/world_bank_projects.json')))
data = json_normalize(data,'mjtheme_namecode')

#exploring the data 
data.sort_values(["code", "name"], axis=0,ascending=True, inplace=True) 

#Looking at the head and tail 
print(data.head())
print(data.tail())

#replace the blank values with NaN with regular Expression 
data=data.replace(r'^\s*$', np.nan, regex=True)

#seeing the codes that match with the project name
duplicate_data =  data.drop_duplicates(['code','name'])

#dropped duplciate values 
duplicate_data = duplicate_data.dropna(how = 'any')

#printed the results sorted the order by code then name in descending order 
print(duplicate_data.sort_values(['code','name'],ascending = True))

#Turning the code section from string to numeric 
data['code'] = pd.to_numeric(data['code'], errors='coerce')

#Changed project name based on code using .loc 
data.loc[data['code'] == 1, ['name']] = 'Economic management'
data.loc[data['code'] == 10, ['name']] = 'Rural development'
data.loc[data['code'] == 11, ['name']] = 'Environment and natural resource management'
data.loc[data['code'] == 2, ['name']] = 'Public Sector governance'
data.loc[data['code'] == 3, ['name']] = 'Rule of Law'
data.loc[data['code'] == 4, ['name']] = 'Financial and private sector development'
data.loc[data['code'] == 5, ['name']] = 'Trade and intergration'
data.loc[data['code'] == 6, ['name']] = 'Social protection and risk management'
data.loc[data['code'] == 7, ['name']] = 'Social dev/gender/inclusion'
data.loc[data['code'] == 8, ['name']] = 'Human development'
data.loc[data['code'] == 9, ['name']] = 'Urban Development'

d1 = data.groupby('name').size()
print(d1.sort_values(ascending=False).head(10))

     code name
212     1
363     1
1024    1
1114    1
1437    1
     code               name
1426    9  Urban development
1428    9  Urban development
1470    9  Urban development
1473    9  Urban development
1495    9  Urban development
    code                                          name
2      1                           Economic management
18    10                             Rural development
6     11  Environment and natural resources management
5      2                      Public sector governance
252    3                                   Rule of law
11     4      Financial and private sector development
4      5                         Trade and integration
3      6         Social protection and risk management
8      7                   Social dev/gender/inclusion
0      8                             Human development
53     9                             Urban development
      code                 name
212      1  Economic management
363      1  Economic management
1024     1  Economic management
1114     1  Economic management
1437     1  Economic management
2        1  Economic management
88       1  Economic management
175      1  Economic management
204      1  Economic management
205      1  Economic management
220      1  Economic management
222      1  Economic management
223      1  Economic management
249      1  Economic management
357      1  Economic management
453      1  Economic management
454      1  Economic management
458      1  Economic management
497      1  Economic management
647      1  Economic management
648      1  Economic management
784      1  Economic management
803      1  Economic management
841      1  Economic management
900      1  Economic management
1010     1  Economic management
1045     1  Economic management
1056     1  Economic management
1057     1  Economic management
1078     1  Economic management
...    ...                  ...
597      9    Urban Development
598      9    Urban Development
650      9    Urban Development
669      9    Urban Development
732      9    Urban Development
737      9    Urban Development
738      9    Urban Development
739      9    Urban Development
742      9    Urban Development
822      9    Urban Development
917      9    Urban Development
930      9    Urban Development
940      9    Urban Development
962      9    Urban Development
1095     9    Urban Development
1102     9    Urban Development
1103     9    Urban Development
1104     9    Urban Development
1166     9    Urban Development
1290     9    Urban Development
1303     9    Urban Development
1318     9    Urban Development
1342     9    Urban Development
1347     9    Urban Development
1425     9    Urban Development
1426     9    Urban Development
1428     9    Urban Development
1470     9    Urban Development
1473     9    Urban Development
1495     9    Urban Development

[1499 rows x 2 columns]
name
Environment and natural resource management    250
Rural development                              216
Human development                              210
Public Sector governance                       199
Social protection and risk management          168
Financial and private sector development       146
Social dev/gender/inclusion                    130
Trade and intergration                          77
Urban Development                               50
Economic management                             38
dtype: int64

## Questoin 3 - Create a dataframe with the missing names filled in
1. Created a dataframe df1
2. reset the index so name wouldn't be the index
3. Changed the column names
4. Printed the results

In [37]:
#creating a dataframe 
df1 = pd.DataFrame(d1)
#had to reset the index so name wouldn't be the index 
df1 = df1.reset_index()
df1.columns = ['Project Name','Count']
print(df1.sort_values('Count',ascending = False))

                                   Project Name  Count
1   Environment and natural resource management    250
6                             Rural development    216
3                             Human development    210
4                      Public Sector governance    199
8         Social protection and risk management    168
2      Financial and private sector development    146
7                   Social dev/gender/inclusion    130
9                        Trade and intergration     77
10                            Urban Development     50
0                           Economic management     38
5                                   Rule of Law     15